import { signIn, signOut, useSession } from "next-auth/react";
import { useTranslation } from "next-i18next";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import Landing from "~/views/landing/landing";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const { t } = useTranslation(["translation", "landing"]);

  return (
    <>
      <Head>
        <title>Infomatics Expo</title>
        <meta name="description" content="Generated by create-t3-app" />
        <meta name="robots" content="index, follow" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div id="#maincontent">
        <Landing />
      </div>
    </>
  );
}
